### ISSUE TITLE
Non-ASCII breaks md_to_json (Support Unicode)

### ISSUE THREAD

**Issue by eshao** [njvack/bids-json-writer#1]
I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/md_to_json", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/scripts/md_to_json.py", line 89, in main
    indent)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/scripts/md_to_json.py", line 68, in jsonify_markdown
    rendered = renderer.stringify_dict(nested)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 114, in stringify_dict
    for k, v in d.items()
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 120, in _valuify
    return self.stringify_dict(cm_vals)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 114, in stringify_dict
    for k, v in d.items()
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 120, in _valuify
    return self.stringify_dict(cm_vals)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 114, in stringify_dict
    for k, v in d.items()
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 120, in _valuify
    return self.stringify_dict(cm_vals)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 114, in stringify_dict
    for k, v in d.items()
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 133, in _render_block
    return method(block)
  File "/usr/local/lib/python2.7/site-packages/markdown_to_json/markdown_to_json.py", line 137, in _render_generic_block
    return "\n".join(block.strings)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 83: ordinal not in range(128)
```

When passing in this string:
`#### When someone unexpectedly hands over to you in the middle of a presentation and you’ve never even seen the slides before`

If I change the `’` to `'`, the error goes away and it works fine. Similarly, Chinese characters or anything non-ASCII also breaks md-to-json.

**Comment by njvack** [comment]
Boo! This is python 2.x, right?

**Comment by ArtursO** [comment]
@njvack I'm getting this error with Python 2.7.10 :(

**Comment by Scott-zhangjs** [comment]
The error is made by UnicodeDecodeError.
In the file of markdown_to_json.py, line 137, return "\n".join(block.strings)
change to:
tmp = []
for n in block.strings:
    tmp.append(n.decode('utf8'))
return "\n".join(tmp)

**Comment by njvack** [comment]
Hi! Please accept my apology for letting this sit idle for so long — I started thinking about this and then python3 and my brain got out of hand.

I'll try and find time to merge the PR and test it out in the next few days.

**Comment by matthewdeanmartin** [comment]
Merged and python 3 compatible. Maintaining python 2.7 compatibility might require a different library or branch. Last I checked it is less than 5% of remaining users.

**Comment by njvack** [comment]
I am fine if we drop py2 support entirely at this point. People can always use version 1.0 of the library if needed.

**Comment by matthewdeanmartin** [comment]
Oh good. Supporting 2/3 was a major project back when I had to do it. I'll update the build script.
