### ISSUE TITLE
Can't use item list

### ISSUE THREAD

**Issue by daixtrose** [njvack/bids-json-writer#4]
Consider this markdown:

```markdown
## GUID

2db62bb2-8ac0-4137-b26f-78a12bff449d

## Title

Some title

## Summary

A Summary
## Priority

- Must

## Detailed Description

- Lorem Ipsum Blabla
- Lorem Ipsum Blabla 

## Reference Requirements

> na

## Categories

- Cat6
```
The command `md_to_json Test.md` yields

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\md_to_json-script.py", line 11, in <module>
    load_entry_point('markdown-to-json==1.0.0', 'console_scripts', 'md_to_json')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\markdown_to_json-1.0.0-py3.6.egg\markdown_to_json\scripts\md_to_json.py", line 94, in main
  File "C:\ProgramData\Anaconda3\lib\site-packages\markdown_to_json-1.0.0-py3.6.egg\markdown_to_json\scripts\md_to_json.py", line 72, in jsonify_markdown
  File "C:\ProgramData\Anaconda3\lib\site-packages\markdown_to_json-1.0.0-py3.6.egg\markdown_to_json\markdown_to_json.py", line 59, in nest
  File "C:\ProgramData\Anaconda3\lib\site-packages\markdown_to_json-1.0.0-py3.6.egg\markdown_to_json\markdown_to_json.py", line 66, in _dictify_blocks
  File "C:\ProgramData\Anaconda3\lib\site-packages\markdown_to_json-1.0.0-py3.6.egg\markdown_to_json\markdown_to_json.py", line 80, in _ensure_list_singleton
markdown_to_json.markdown_to_json.ContentError: Error at line 14: Can't mix lists and other content
```

**Comment by njvack** [comment]
What if you add a blank line between "A Summary" and "## Priority"?

**Comment by matthewdeanmartin** [comment]
I updated it to not blow up, but it doesn't return anything sensible. I think it is because the library expect a `#` level before `##`. I'll see about updating it to handle that scenario.

**Comment by matthewdeanmartin** [comment]
In the [markpickle](https://pypi.org/project/markpickle) library it can parse it to something sensible, [see here](https://github.com/matthewdeanmartin/markpickle/blob/main/test/test_deserialize/markdown_to_json_examples/mixed/issue_8.py).

So there is a way to make it happen, I'll see if I can apply the same sort of fix here. It will have to wait for a weekend though.

**Comment by njvack** [comment]
yeah I'm not entirely sure what to expect if the headings _start_ at two levels of indent. Maybe

```
## key

value
```

would parse as

```
{ "" => {"key" => "value" } }
```

but that's weird

I guess we could promote headers to the first unused level (if there's no h1 in the doc, promote h2 to h1 and so on), but that seems like overcomplicated weird behavior

My take is: don't skip heading levels in your markdown

**Comment by njvack** [comment]
Yeah that is a reasonable fix, thanks!
